version: '3'

vars:
  COMPOSE_FILE: deploy/compose/compose.dev.yaml
  CONTAINER: pressograph-dev-workspace

tasks:
  # Environment and secrets management
  secrets:generate:
    desc: Generate secure secrets for .env.local
    cmds:
      - chmod +x deploy/scripts/generate-secrets.sh
      - ./deploy/scripts/generate-secrets.sh

  secrets:generate:prod:
    desc: Generate production secrets
    cmds:
      - chmod +x deploy/scripts/generate-secrets.sh
      - ./deploy/scripts/generate-secrets.sh --env prod

  secrets:rotate:
    desc: Rotate all secrets (regenerate .env.local)
    cmds:
      - rm -f .env.local
      - task: secrets:generate

  env:template:
    desc: Copy environment template
    cmds:
      - |
        if [ ! -f .env.local ]; then
          cp .env.dev.example .env.local
          echo "Created .env.local from template"
          echo "IMPORTANT: Run 'task secrets:generate' to generate secure secrets"
        else
          echo ".env.local already exists. Use 'task secrets:rotate' to regenerate."
        fi

  # Development environment management
  dev:setup:
    desc: Setup development environment
    cmds:
      - chmod +x deploy/scripts/*.sh
      - ./deploy/scripts/dev-setup.sh

  dev:start:
    desc: Start development containers
    cmds:
      - podman-compose -f {{.COMPOSE_FILE}} up -d

  dev:stop:
    desc: Stop development containers
    cmds:
      - podman-compose -f {{.COMPOSE_FILE}} stop

  dev:restart:
    desc: Restart development containers
    cmds:
      - task: dev:stop
      - task: dev:start

  dev:enter:
    desc: Enter development container
    cmds:
      - ./deploy/scripts/dev-enter.sh

  dev:logs:
    desc: View development container logs
    cmds:
      - ./deploy/scripts/dev-logs.sh {{.CLI_ARGS}}

  dev:destroy:
    desc: Destroy development environment
    cmds:
      - ./deploy/scripts/dev-destroy.sh

  dev:rebuild:
    desc: Rebuild development environment
    cmds:
      - task: dev:destroy
      - task: dev:setup

  # Container execution
  exec:
    desc: Execute command in dev container
    cmds:
      - podman exec -it {{.CONTAINER}} {{.CLI_ARGS}}

  exec:root:
    desc: Execute command as root in dev container
    cmds:
      - podman exec -it -u root {{.CONTAINER}} {{.CLI_ARGS}}

  # Next.js commands
  dev:next:
    desc: Start Next.js dev server
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm dev

  build:
    desc: Build Next.js application
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm build

  start:
    desc: Start production Next.js server
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm start

  # Package management
  install:
    desc: Install dependencies
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm install

  update:
    desc: Update dependencies
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm update

  # Database commands
  db:push:
    desc: Push database schema
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm db:push

  db:studio:
    desc: Open Drizzle Studio
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm db:studio

  db:migrate:
    desc: Generate migrations
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm db:generate

  db:seed:
    desc: Seed database
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm db:seed

  # Code quality
  lint:
    desc: Run ESLint
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm lint

  lint:fix:
    desc: Fix ESLint errors
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm lint:fix

  format:
    desc: Format code with Prettier
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm format

  type-check:
    desc: Run TypeScript type checking
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm type-check

  # Testing
  test:
    desc: Run tests
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm test

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm test:watch

  test:coverage:
    desc: Generate test coverage
    cmds:
      - podman exec -it {{.CONTAINER}} pnpm test:coverage

  # Observability (OpenTelemetry + VictoriaMetrics)
  metrics:start:
    desc: Start VictoriaMetrics observability stack
    cmds:
      - podman-compose -f deploy/compose/compose.victoria.yaml up -d
      - echo "VictoriaMetrics stack started"
      - echo "  Grafana - https://dev-grafana.infra4.dev (admin/admin)"
      - echo "  VictoriaMetrics - https://dev-vm.infra4.dev"
      - echo "  VictoriaLogs - https://dev-vl.infra4.dev"
      - echo "  VictoriaTraces - https://dev-vt.infra4.dev"

  metrics:stop:
    desc: Stop VictoriaMetrics observability stack
    cmds:
      - podman-compose -f deploy/compose/compose.victoria.yaml down

  metrics:restart:
    desc: Restart VictoriaMetrics observability stack
    cmds:
      - task: metrics:stop
      - task: metrics:start

  metrics:logs:
    desc: View VictoriaMetrics stack logs
    cmds:
      - podman-compose -f deploy/compose/compose.victoria.yaml logs -f {{.CLI_ARGS}}

  metrics:status:
    desc: Show VictoriaMetrics stack status
    cmds:
      - podman-compose -f deploy/compose/compose.victoria.yaml ps

  grafana:open:
    desc: Open Grafana in browser
    cmds:
      - open https://dev-grafana.infra4.dev || xdg-open https://dev-grafana.infra4.dev || echo "Open https://dev-grafana.infra4.dev manually"

  # Uptrace (OpenTelemetry APM)
  uptrace:start:
    desc: Start Uptrace observability stack
    cmds:
      - podman-compose -f deploy/compose/compose.uptrace.yaml up -d
      - echo "Uptrace stack started"
      - echo "  Uptrace UI - https://dev-uptrace.infra4.dev"
      - echo "  OTLP gRPC  - localhost:14317"
      - echo "  OTLP HTTP  - localhost:14318"

  uptrace:stop:
    desc: Stop Uptrace observability stack
    cmds:
      - podman-compose -f deploy/compose/compose.uptrace.yaml down

  uptrace:restart:
    desc: Restart Uptrace observability stack
    cmds:
      - task: uptrace:stop
      - task: uptrace:start

  uptrace:logs:
    desc: View Uptrace stack logs
    cmds:
      - podman-compose -f deploy/compose/compose.uptrace.yaml logs -f {{.CLI_ARGS}}

  uptrace:status:
    desc: Show Uptrace stack status
    cmds:
      - podman-compose -f deploy/compose/compose.uptrace.yaml ps

  uptrace:open:
    desc: Open Uptrace in browser
    cmds:
      - open https://dev-uptrace.infra4.dev || xdg-open https://dev-uptrace.infra4.dev || echo "Open https://dev-uptrace.infra4.dev manually"

  # Container status
  ps:
    desc: Show container status
    cmds:
      - podman-compose -f {{.COMPOSE_FILE}} ps

  stats:
    desc: Show container resource usage
    cmds:
      - podman stats pressograph-dev-workspace pressograph-dev-db pressograph-dev-cache
