# ═══════════════════════════════════════════════════════════════════
# Grafana Datasource: VictoriaMetrics (Prometheus-compatible)
# ═══════════════════════════════════════════════════════════════════
# Этот файл автоматически настраивает VictoriaMetrics как datasource
# при старте Grafana (provisioning)
#
# VictoriaMetrics полностью совместим с Prometheus API, поэтому
# используется datasource type: prometheus
# ═══════════════════════════════════════════════════════════════════

apiVersion: 1

datasources:
  # VictoriaMetrics для метрик (замена Prometheus)
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true  # Default datasource для метрик
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      # Prometheus-compatible query hints
      prometheusType: Prometheus
      prometheusVersion: 2.50.0
      # Query optimization
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
      # Caching
      cacheLevel: High
      # Exemplars support (для трейсов)
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
    version: 1
