version: '3.8'

services:
  # ═══════════════════════════════════════════════
  # Production Frontend (Nginx with Traefik)
  # ═══════════════════════════════════════════════
  frontend-prod:
    build:
      context: ../../
      dockerfile: deploy/Containerfile
    image: pressure-test-visualizer:latest
    container_name: pressure-test-visualizer-prod
    networks:
      - traefik-public
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    labels:
      - "traefik.enable=true"
      # HTTPS Router
      - "traefik.http.routers.pressure-test.entrypoints=https"
      - "traefik.http.routers.pressure-test.rule=Host(`dev-graph.infra4.dev`)"
      - "traefik.http.routers.pressure-test.tls=true"
      - "traefik.http.routers.pressure-test.tls.certresolver=cloudflare"
      # Apply web-standard middleware chain (security headers, compression, rate limiting)
      - "traefik.http.routers.pressure-test.middlewares=web-standard@file"
      # Service configuration
      - "traefik.http.services.pressure-test.loadbalancer.server.port=80"
      - "traefik.http.services.pressure-test.loadbalancer.server.scheme=http"
      - "traefik.http.services.pressure-test.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.pressure-test.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.pressure-test.loadbalancer.healthcheck.timeout=3s"
      # Network
      - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true
